model {
  file: "model.sdf"
}
name: "Calphalon_Kitchen_Essentials_12_Cast_Iron_Fry_Pan_Black"
description: "Calphalon Kitchen Essentials 12\" Cast Iron Fry Pan, Black"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Calphalon"
}
annotations {
  key: "gtin"
  value: "00727870053867"
}
annotations {
  key: "sku"
  value: "00727870053867"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
}
